spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://ep-late-mountain-ami1fmbj-pooler.c-5.us-east-1.aws.neon.tech/user_service_db?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_kJEMe1DKpw8i
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  jackson:
    serialization:
      write-dates-as-timestamps: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 8081

logging:
  level:
    root: INFO
    com.marketplace: DEBUG
